-- API-Football v3 normalized ingestion schema.
--
-- Compatibility contract:
--   * public.fixtures.id remains the API-Football fixture id and the primary key.
--   * Existing foreign keys from predictions and prediction_versions are untouched.
--   * Legacy fixtures.league_id/kickoff/raw_payload remain available.
--   * New ingestion code should upsert fixtures on api_fixture_id.

create table public.competitions (
  id bigint generated by default as identity primary key,
  api_league_id bigint unique,
  internal_code text not null unique,
  name text not null,
  country text not null,
  competition_type text not null,
  logo_url text,
  enabled boolean not null default true,
  last_synced_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint competitions_api_league_id_positive check (
    api_league_id is null or api_league_id > 0
  ),
  constraint competitions_internal_code_not_blank check (btrim(internal_code) <> ''),
  constraint competitions_name_not_blank check (btrim(name) <> ''),
  constraint competitions_country_not_blank check (btrim(country) <> ''),
  constraint competitions_type_valid check (competition_type in ('league', 'cup'))
);

-- Preserve the five existing European competitions while adopting stable internal codes.
insert into public.competitions (
  id,
  api_league_id,
  internal_code,
  name,
  country,
  competition_type,
  enabled,
  created_at,
  updated_at
)
select
  l.id,
  l.id,
  case l.id
    when 39 then 'premier_league'
    when 61 then 'ligue_1'
    when 78 then 'bundesliga'
    when 135 then 'serie_a_italy'
    when 140 then 'laliga'
    else 'legacy_league_' || l.id::text
  end,
  l.name,
  l.country,
  'league',
  l.enabled,
  l.created_at,
  l.updated_at
from public.leagues as l;

select pg_catalog.setval(
  pg_catalog.pg_get_serial_sequence('public.competitions', 'id'),
  greatest(coalesce((select max(id) from public.competitions), 1), 1),
  exists (select 1 from public.competitions)
);

create table public.competition_seasons (
  id bigint generated always as identity primary key,
  competition_id bigint not null references public.competitions(id) on delete cascade,
  season integer not null,
  start_date date,
  end_date date,
  is_current boolean not null default false,
  coverage_json jsonb not null default '{}'::jsonb,
  availability_status text not null default 'pending',
  last_synced_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint competition_seasons_competition_season_key unique (competition_id, season),
  constraint competition_seasons_season_reasonable check (season between 2000 and 2100),
  constraint competition_seasons_dates_ordered check (
    start_date is null or end_date is null or start_date <= end_date
  ),
  constraint competition_seasons_coverage_object check (
    jsonb_typeof(coverage_json) = 'object'
  ),
  constraint competition_seasons_availability_valid check (
    availability_status in (
      'pending',
      'available',
      'unavailable',
      'plan_restricted',
      'error'
    )
  )
);

insert into public.competition_seasons (
  competition_id,
  season,
  availability_status,
  last_synced_at
)
select distinct
  c.id,
  f.season,
  'available',
  now()
from public.fixtures as f
join public.competitions as c on c.api_league_id = f.league_id
on conflict (competition_id, season) do nothing;

create table public.teams (
  id bigint generated by default as identity primary key,
  api_team_id bigint not null unique,
  name text not null,
  code text,
  country text,
  founded integer,
  national boolean,
  logo_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint teams_api_team_id_positive check (api_team_id > 0),
  constraint teams_name_not_blank check (btrim(name) <> ''),
  constraint teams_code_not_blank check (code is null or btrim(code) <> ''),
  constraint teams_country_not_blank check (country is null or btrim(country) <> ''),
  constraint teams_founded_reasonable check (
    founded is null or founded between 1800 and 2100
  )
);

-- Existing fixture team ids are API-Football ids. Seed matching surrogate rows so
-- adding normalized foreign keys does not rewrite or invalidate existing fixtures.
insert into public.teams (id, api_team_id, name)
select
  source.api_team_id,
  source.api_team_id,
  max(source.team_name)
from (
  select home_team_id as api_team_id, home_team_name as team_name
  from public.fixtures
  union all
  select away_team_id as api_team_id, away_team_name as team_name
  from public.fixtures
) as source
group by source.api_team_id;

select pg_catalog.setval(
  pg_catalog.pg_get_serial_sequence('public.teams', 'id'),
  greatest(coalesce((select max(id) from public.teams), 1), 1),
  exists (select 1 from public.teams)
);

create table public.venues (
  id bigint generated always as identity primary key,
  api_venue_id bigint unique,
  name text,
  city text,
  address text,
  capacity integer,
  surface text,
  image_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint venues_api_venue_id_positive check (
    api_venue_id is null or api_venue_id > 0
  ),
  constraint venues_name_not_blank check (name is null or btrim(name) <> ''),
  constraint venues_city_not_blank check (city is null or btrim(city) <> ''),
  constraint venues_capacity_nonnegative check (capacity is null or capacity >= 0)
);

alter table public.fixtures
  add column api_fixture_id bigint,
  add column competition_id bigint,
  add column stage text,
  add column group_name text,
  add column leg text,
  add column fixture_date_utc timestamptz,
  add column fixture_date_lima timestamp without time zone,
  add column "timestamp" bigint,
  add column status_long text,
  add column elapsed smallint,
  add column venue_id bigint,
  add column referee text,
  add column home_team_ref_id bigint,
  add column away_team_ref_id bigint,
  add column home_goals smallint,
  add column away_goals smallint,
  add column halftime_home smallint,
  add column halftime_away smallint,
  add column fulltime_home smallint,
  add column fulltime_away smallint,
  add column extratime_home smallint,
  add column extratime_away smallint,
  add column penalties_home smallint,
  add column penalties_away smallint,
  add column winner_team_id bigint,
  add column winner_team_ref_id bigint,
  add column aggregate_home smallint,
  add column aggregate_away smallint,
  add column raw_json jsonb not null default '{}'::jsonb;

update public.fixtures
set
  api_fixture_id = id,
  competition_id = league_id,
  fixture_date_utc = kickoff,
  fixture_date_lima = kickoff at time zone 'America/Lima',
  "timestamp" = floor(extract(epoch from kickoff))::bigint,
  home_team_ref_id = home_team_id,
  away_team_ref_id = away_team_id,
  raw_json = raw_payload;

alter table public.fixtures
  alter column league_id drop not null,
  alter column api_fixture_id set not null,
  alter column competition_id set not null,
  alter column fixture_date_utc set not null,
  add constraint fixtures_api_fixture_id_key unique (api_fixture_id),
  add constraint fixtures_api_fixture_id_positive check (api_fixture_id > 0),
  add constraint fixtures_competition_id_fkey
    foreign key (competition_id) references public.competitions(id),
  add constraint fixtures_home_team_ref_id_fkey
    foreign key (home_team_ref_id) references public.teams(id),
  add constraint fixtures_away_team_ref_id_fkey
    foreign key (away_team_ref_id) references public.teams(id),
  add constraint fixtures_venue_id_fkey
    foreign key (venue_id) references public.venues(id) on delete set null,
  add constraint fixtures_winner_team_ref_id_fkey
    foreign key (winner_team_ref_id) references public.teams(id) on delete set null,
  add constraint fixtures_elapsed_valid check (
    elapsed is null or elapsed between 0 and 200
  ),
  add constraint fixtures_leg_valid check (
    leg is null or leg in (
      'single',
      'first',
      'second',
      'first_leg',
      'second_leg',
      'replay',
      'unknown'
    )
  ),
  add constraint fixtures_winner_team_id_positive check (
    winner_team_id is null or winner_team_id > 0
  ),
  add constraint fixtures_scores_nonnegative check (
    (home_goals is null or home_goals >= 0)
    and (away_goals is null or away_goals >= 0)
    and (halftime_home is null or halftime_home >= 0)
    and (halftime_away is null or halftime_away >= 0)
    and (fulltime_home is null or fulltime_home >= 0)
    and (fulltime_away is null or fulltime_away >= 0)
    and (extratime_home is null or extratime_home >= 0)
    and (extratime_away is null or extratime_away >= 0)
    and (penalties_home is null or penalties_home >= 0)
    and (penalties_away is null or penalties_away >= 0)
    and (aggregate_home is null or aggregate_home >= 0)
    and (aggregate_away is null or aggregate_away >= 0)
  ),
  add constraint fixtures_raw_json_object check (jsonb_typeof(raw_json) = 'object');

create function public.sync_fixture_compatibility()
returns trigger
language plpgsql
security invoker
set search_path = pg_catalog
as $$
begin
  if tg_op = 'INSERT' then
    new.id := coalesce(new.id, new.api_fixture_id);
    new.api_fixture_id := coalesce(new.api_fixture_id, new.id);

    if new.competition_id is null and new.league_id is not null then
      select c.id
      into new.competition_id
      from public.competitions as c
      where c.api_league_id = new.league_id;
    end if;

    if new.league_id is null and new.competition_id is not null then
      select l.id
      into new.league_id
      from public.competitions as c
      join public.leagues as l on l.id = c.api_league_id
      where c.id = new.competition_id;
    end if;

    new.kickoff := coalesce(new.kickoff, new.fixture_date_utc);
    new.fixture_date_utc := coalesce(new.fixture_date_utc, new.kickoff);

    if new.home_team_ref_id is null and new.home_team_id is not null then
      select t.id into new.home_team_ref_id
      from public.teams as t
      where t.api_team_id = new.home_team_id;
    elsif new.home_team_id is null and new.home_team_ref_id is not null then
      select t.api_team_id into new.home_team_id
      from public.teams as t
      where t.id = new.home_team_ref_id;
    end if;

    if new.away_team_ref_id is null and new.away_team_id is not null then
      select t.id into new.away_team_ref_id
      from public.teams as t
      where t.api_team_id = new.away_team_id;
    elsif new.away_team_id is null and new.away_team_ref_id is not null then
      select t.api_team_id into new.away_team_id
      from public.teams as t
      where t.id = new.away_team_ref_id;
    end if;

    if new.winner_team_ref_id is null and new.winner_team_id is not null then
      select t.id into new.winner_team_ref_id
      from public.teams as t
      where t.api_team_id = new.winner_team_id;
    elsif new.winner_team_id is null and new.winner_team_ref_id is not null then
      select t.api_team_id into new.winner_team_id
      from public.teams as t
      where t.id = new.winner_team_ref_id;
    end if;

    if new.raw_json = '{}'::jsonb and new.raw_payload <> '{}'::jsonb then
      new.raw_json := new.raw_payload;
    elsif new.raw_payload = '{}'::jsonb and new.raw_json <> '{}'::jsonb then
      new.raw_payload := new.raw_json;
    elsif new.raw_json <> new.raw_payload then
      new.raw_payload := new.raw_json;
    end if;
  else
    if new.id is distinct from old.id or new.api_fixture_id is distinct from old.api_fixture_id then
      raise exception 'Fixture identifiers are immutable';
    end if;

    if new.competition_id is distinct from old.competition_id then
      select l.id
      into new.league_id
      from public.competitions as c
      join public.leagues as l on l.id = c.api_league_id
      where c.id = new.competition_id;
    elsif new.league_id is distinct from old.league_id and new.league_id is not null then
      select c.id
      into new.competition_id
      from public.competitions as c
      where c.api_league_id = new.league_id;
    end if;

    if new.fixture_date_utc is distinct from old.fixture_date_utc then
      new.kickoff := new.fixture_date_utc;
    elsif new.kickoff is distinct from old.kickoff then
      new.fixture_date_utc := new.kickoff;
    end if;

    if new.home_team_id is distinct from old.home_team_id then
      select t.id into new.home_team_ref_id
      from public.teams as t
      where t.api_team_id = new.home_team_id;
    elsif new.home_team_ref_id is distinct from old.home_team_ref_id then
      select t.api_team_id into new.home_team_id
      from public.teams as t
      where t.id = new.home_team_ref_id;
    end if;

    if new.away_team_id is distinct from old.away_team_id then
      select t.id into new.away_team_ref_id
      from public.teams as t
      where t.api_team_id = new.away_team_id;
    elsif new.away_team_ref_id is distinct from old.away_team_ref_id then
      select t.api_team_id into new.away_team_id
      from public.teams as t
      where t.id = new.away_team_ref_id;
    end if;

    if new.winner_team_id is distinct from old.winner_team_id then
      select t.id into new.winner_team_ref_id
      from public.teams as t
      where t.api_team_id = new.winner_team_id;
    elsif new.winner_team_ref_id is distinct from old.winner_team_ref_id then
      select t.api_team_id into new.winner_team_id
      from public.teams as t
      where t.id = new.winner_team_ref_id;
    end if;

    if new.raw_json is distinct from old.raw_json then
      new.raw_payload := new.raw_json;
    elsif new.raw_payload is distinct from old.raw_payload then
      new.raw_json := new.raw_payload;
    end if;
  end if;

  new.fixture_date_lima := new.fixture_date_utc at time zone 'America/Lima';
  new."timestamp" := floor(extract(epoch from new.fixture_date_utc))::bigint;
  return new;
end;
$$;

create trigger fixtures_sync_compatibility
before insert or update on public.fixtures
for each row execute function public.sync_fixture_compatibility();

create table public.fixture_events (
  id bigint generated always as identity primary key,
  fixture_id bigint not null references public.fixtures(id) on delete cascade,
  event_order smallint not null,
  api_team_id bigint,
  api_player_id bigint,
  api_assist_id bigint,
  minute smallint,
  extra_minute smallint,
  event_type text not null,
  detail text,
  comments text,
  raw_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint fixture_events_fixture_order_key unique (fixture_id, event_order),
  constraint fixture_events_order_nonnegative check (event_order >= 0),
  constraint fixture_events_api_ids_positive check (
    (api_team_id is null or api_team_id > 0)
    and (api_player_id is null or api_player_id > 0)
    and (api_assist_id is null or api_assist_id > 0)
  ),
  constraint fixture_events_minute_valid check (
    (minute is null or minute between 0 and 200)
    and (extra_minute is null or extra_minute between 0 and 100)
  ),
  constraint fixture_events_type_not_blank check (btrim(event_type) <> ''),
  constraint fixture_events_raw_object check (jsonb_typeof(raw_json) = 'object')
);

create table public.fixture_team_statistics (
  fixture_id bigint not null references public.fixtures(id) on delete cascade,
  team_id bigint not null references public.teams(id),
  is_home boolean not null,
  shots_on_goal integer,
  shots_off_goal integer,
  total_shots integer,
  blocked_shots integer,
  shots_inside_box integer,
  shots_outside_box integer,
  fouls integer,
  corners integer,
  offsides integer,
  possession_percentage numeric(5, 2),
  yellow_cards integer,
  red_cards integer,
  goalkeeper_saves integer,
  total_passes integer,
  passes_accurate integer,
  passes_percentage numeric(5, 2),
  expected_goals numeric(7, 3),
  raw_statistics_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (fixture_id, team_id),
  constraint fixture_team_statistics_counts_nonnegative check (
    (shots_on_goal is null or shots_on_goal >= 0)
    and (shots_off_goal is null or shots_off_goal >= 0)
    and (total_shots is null or total_shots >= 0)
    and (blocked_shots is null or blocked_shots >= 0)
    and (shots_inside_box is null or shots_inside_box >= 0)
    and (shots_outside_box is null or shots_outside_box >= 0)
    and (fouls is null or fouls >= 0)
    and (corners is null or corners >= 0)
    and (offsides is null or offsides >= 0)
    and (yellow_cards is null or yellow_cards >= 0)
    and (red_cards is null or red_cards >= 0)
    and (goalkeeper_saves is null or goalkeeper_saves >= 0)
    and (total_passes is null or total_passes >= 0)
    and (passes_accurate is null or passes_accurate >= 0)
    and (expected_goals is null or expected_goals >= 0)
  ),
  constraint fixture_team_statistics_percentages_valid check (
    (possession_percentage is null or possession_percentage between 0 and 100)
    and (passes_percentage is null or passes_percentage between 0 and 100)
  ),
  constraint fixture_team_statistics_raw_object check (
    jsonb_typeof(raw_statistics_json) in ('object', 'array')
  )
);

create table public.players (
  id bigint generated always as identity primary key,
  api_player_id bigint not null unique,
  name text not null,
  firstname text,
  lastname text,
  age smallint,
  birth_date date,
  nationality text,
  height text,
  weight text,
  injured boolean,
  photo_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint players_api_player_id_positive check (api_player_id > 0),
  constraint players_name_not_blank check (btrim(name) <> ''),
  constraint players_age_reasonable check (age is null or age between 10 and 80)
);

create table public.fixture_player_statistics (
  fixture_id bigint not null references public.fixtures(id) on delete cascade,
  player_id bigint not null references public.players(id),
  team_id bigint not null references public.teams(id),
  position text,
  starter boolean,
  captain boolean,
  substitute boolean,
  minutes integer,
  rating numeric(4, 2),
  shots_total integer,
  shots_on integer,
  goals integer,
  assists integer,
  saves integer,
  passes_total integer,
  passes_key integer,
  passes_accuracy numeric(5, 2),
  tackles_total integer,
  interceptions integer,
  duels_total integer,
  duels_won integer,
  dribbles_attempts integer,
  dribbles_success integer,
  fouls_drawn integer,
  fouls_committed integer,
  yellow_cards integer,
  red_cards integer,
  penalty_won integer,
  penalty_committed integer,
  penalty_scored integer,
  penalty_missed integer,
  penalty_saved integer,
  raw_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (fixture_id, player_id, team_id),
  constraint fixture_player_statistics_minutes_valid check (
    minutes is null or minutes between 0 and 200
  ),
  constraint fixture_player_statistics_rating_valid check (
    rating is null or rating between 0 and 10
  ),
  constraint fixture_player_statistics_passes_accuracy_valid check (
    passes_accuracy is null or passes_accuracy between 0 and 100
  ),
  constraint fixture_player_statistics_counts_nonnegative check (
    (shots_total is null or shots_total >= 0)
    and (shots_on is null or shots_on >= 0)
    and (goals is null or goals >= 0)
    and (assists is null or assists >= 0)
    and (saves is null or saves >= 0)
    and (passes_total is null or passes_total >= 0)
    and (passes_key is null or passes_key >= 0)
    and (tackles_total is null or tackles_total >= 0)
    and (interceptions is null or interceptions >= 0)
    and (duels_total is null or duels_total >= 0)
    and (duels_won is null or duels_won >= 0)
    and (dribbles_attempts is null or dribbles_attempts >= 0)
    and (dribbles_success is null or dribbles_success >= 0)
    and (fouls_drawn is null or fouls_drawn >= 0)
    and (fouls_committed is null or fouls_committed >= 0)
    and (yellow_cards is null or yellow_cards >= 0)
    and (red_cards is null or red_cards >= 0)
    and (penalty_won is null or penalty_won >= 0)
    and (penalty_committed is null or penalty_committed >= 0)
    and (penalty_scored is null or penalty_scored >= 0)
    and (penalty_missed is null or penalty_missed >= 0)
    and (penalty_saved is null or penalty_saved >= 0)
  ),
  constraint fixture_player_statistics_raw_object check (
    jsonb_typeof(raw_json) = 'object'
  )
);

create table public.lineups (
  id bigint generated always as identity primary key,
  fixture_id bigint not null references public.fixtures(id) on delete cascade,
  team_id bigint not null references public.teams(id),
  formation text,
  coach_api_id bigint,
  coach_name text,
  confirmed boolean not null default false,
  fetched_at timestamptz not null default now(),
  raw_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint lineups_fixture_team_key unique (fixture_id, team_id),
  constraint lineups_coach_api_id_positive check (
    coach_api_id is null or coach_api_id > 0
  ),
  constraint lineups_formation_not_blank check (
    formation is null or btrim(formation) <> ''
  ),
  constraint lineups_raw_object check (jsonb_typeof(raw_json) = 'object')
);

create table public.lineup_players (
  id bigint generated always as identity primary key,
  lineup_id bigint not null references public.lineups(id) on delete cascade,
  lineup_order smallint not null,
  player_id bigint references public.players(id),
  api_player_id bigint,
  player_name text not null,
  number smallint,
  position text,
  grid_position text,
  starter boolean not null default false,
  substitute boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint lineup_players_lineup_order_key unique (lineup_id, lineup_order),
  constraint lineup_players_order_nonnegative check (lineup_order >= 0),
  constraint lineup_players_api_player_id_positive check (
    api_player_id is null or api_player_id > 0
  ),
  constraint lineup_players_name_not_blank check (btrim(player_name) <> ''),
  constraint lineup_players_number_valid check (number is null or number between 0 and 999),
  constraint lineup_players_role_consistent check (not (starter and substitute))
);

create table public.api_sync_status (
  id bigint generated always as identity primary key,
  competition_id bigint not null references public.competitions(id) on delete cascade,
  season integer not null,
  api_fixture_id bigint not null,
  fixture_basic_downloaded boolean not null default false,
  fixture_details_downloaded boolean not null default false,
  statistics_downloaded boolean not null default false,
  players_downloaded boolean not null default false,
  lineups_downloaded boolean not null default false,
  events_downloaded boolean not null default false,
  attempts smallint not null default 0,
  last_attempt_at timestamptz,
  completed_at timestamptz,
  last_error text,
  retry_after timestamptz,
  response_hash text,
  injuries_last_downloaded_at timestamptz,
  odds_last_downloaded_at timestamptz,
  external_prediction_last_downloaded_at timestamptz,
  lineups_next_retry_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint api_sync_status_competition_season_fixture_key unique (
    competition_id,
    season,
    api_fixture_id
  ),
  constraint api_sync_status_season_reasonable check (season between 2000 and 2100),
  constraint api_sync_status_api_fixture_id_positive check (api_fixture_id > 0),
  constraint api_sync_status_attempts_nonnegative check (attempts >= 0),
  constraint api_sync_status_response_hash_not_blank check (
    response_hash is null or btrim(response_hash) <> ''
  )
);

create table public.api_request_logs (
  id bigint generated always as identity primary key,
  endpoint text not null,
  parameters_json jsonb not null default '{}'::jsonb,
  request_hash text not null,
  requested_at timestamptz not null default now(),
  response_status smallint,
  results_count integer,
  daily_limit integer,
  daily_remaining integer,
  minute_limit integer,
  minute_remaining integer,
  duration_ms integer,
  error_message text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint api_request_logs_endpoint_not_blank check (btrim(endpoint) <> ''),
  constraint api_request_logs_hash_not_blank check (btrim(request_hash) <> ''),
  constraint api_request_logs_parameters_object check (
    jsonb_typeof(parameters_json) = 'object'
  ),
  constraint api_request_logs_response_status_valid check (
    response_status is null or response_status between 100 and 599
  ),
  constraint api_request_logs_counters_nonnegative check (
    (results_count is null or results_count >= 0)
    and (daily_limit is null or daily_limit >= 0)
    and (daily_remaining is null or daily_remaining >= 0)
    and (minute_limit is null or minute_limit >= 0)
    and (minute_remaining is null or minute_remaining >= 0)
    and (duration_ms is null or duration_ms >= 0)
  )
);

create table public.fixture_injuries (
  id bigint generated always as identity primary key,
  fixture_id bigint not null references public.fixtures(id) on delete cascade,
  source_key text not null,
  team_id bigint references public.teams(id),
  player_id bigint references public.players(id),
  api_team_id bigint,
  api_player_id bigint,
  injury_type text,
  reason text,
  fetched_at timestamptz not null default now(),
  raw_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint fixture_injuries_fixture_source_key unique (fixture_id, source_key),
  constraint fixture_injuries_source_key_not_blank check (btrim(source_key) <> ''),
  constraint fixture_injuries_api_ids_positive check (
    (api_team_id is null or api_team_id > 0)
    and (api_player_id is null or api_player_id > 0)
  ),
  constraint fixture_injuries_raw_object check (jsonb_typeof(raw_json) = 'object')
);

create table public.fixture_odds_snapshots (
  id bigint generated always as identity primary key,
  fixture_id bigint not null references public.fixtures(id) on delete cascade,
  fetched_at timestamptz not null default now(),
  response_hash text not null,
  raw_json jsonb not null,
  created_at timestamptz not null default now(),
  constraint fixture_odds_snapshots_fixture_hash_key unique (fixture_id, response_hash),
  constraint fixture_odds_snapshots_hash_not_blank check (btrim(response_hash) <> ''),
  constraint fixture_odds_snapshots_raw_object check (jsonb_typeof(raw_json) = 'object')
);

create table public.fixture_external_predictions (
  id bigint generated always as identity primary key,
  fixture_id bigint not null references public.fixtures(id) on delete cascade,
  provider text not null default 'api_football',
  fetched_at timestamptz not null default now(),
  response_hash text not null,
  raw_json jsonb not null,
  created_at timestamptz not null default now(),
  constraint fixture_external_predictions_fixture_provider_hash_key unique (
    fixture_id,
    provider,
    response_hash
  ),
  constraint fixture_external_predictions_provider_not_blank check (btrim(provider) <> ''),
  constraint fixture_external_predictions_hash_not_blank check (btrim(response_hash) <> ''),
  constraint fixture_external_predictions_raw_object check (jsonb_typeof(raw_json) = 'object')
);

create table public.fixture_optional_sync_status (
  fixture_id bigint primary key references public.fixtures(id) on delete cascade,
  injuries_last_fetched_at timestamptz,
  injuries_next_allowed_at timestamptz,
  odds_last_fetched_at timestamptz,
  external_prediction_last_fetched_at timestamptz,
  lineups_last_fetched_at timestamptz,
  lineups_next_retry_at timestamptz,
  lineups_confirmed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Query-path and foreign-key indexes. Unique constraints already index their
-- leftmost columns, so only complementary lookup paths are added here.
create index competition_seasons_status_season_idx
  on public.competition_seasons (availability_status, season desc);
create index teams_country_name_idx on public.teams (country, name);
create index venues_city_name_idx on public.venues (city, name);

create index fixtures_competition_season_date_idx
  on public.fixtures (competition_id, season, fixture_date_utc);
create index fixtures_season_idx on public.fixtures (season);
create index fixtures_fixture_date_utc_idx on public.fixtures (fixture_date_utc);
create index fixtures_home_team_id_idx on public.fixtures (home_team_id);
create index fixtures_away_team_id_idx on public.fixtures (away_team_id);
create index fixtures_home_team_ref_id_idx
  on public.fixtures (home_team_ref_id) where home_team_ref_id is not null;
create index fixtures_away_team_ref_id_idx
  on public.fixtures (away_team_ref_id) where away_team_ref_id is not null;
create index fixtures_venue_id_idx on public.fixtures (venue_id) where venue_id is not null;
create index fixtures_winner_team_id_idx
  on public.fixtures (winner_team_id) where winner_team_id is not null;
create index fixtures_winner_team_ref_id_idx
  on public.fixtures (winner_team_ref_id) where winner_team_ref_id is not null;
create index fixtures_status_short_idx on public.fixtures (status_short);
create index fixtures_upcoming_idx
  on public.fixtures (fixture_date_utc, competition_id)
  where status_short in ('TBD', 'NS', 'PST');

create index fixture_events_api_player_id_idx
  on public.fixture_events (api_player_id) where api_player_id is not null;
create index fixture_team_statistics_team_id_idx
  on public.fixture_team_statistics (team_id);
create index fixture_player_statistics_player_id_idx
  on public.fixture_player_statistics (player_id);
create index fixture_player_statistics_team_id_idx
  on public.fixture_player_statistics (team_id);
create index lineups_team_id_idx on public.lineups (team_id);
create index lineup_players_player_id_idx
  on public.lineup_players (player_id) where player_id is not null;
create index api_sync_status_api_fixture_id_idx
  on public.api_sync_status (api_fixture_id);
create index api_sync_status_retry_idx
  on public.api_sync_status (retry_after, last_attempt_at)
  where completed_at is null;
create index api_request_logs_requested_at_idx
  on public.api_request_logs (requested_at desc);
create index api_request_logs_request_hash_idx
  on public.api_request_logs (request_hash, requested_at desc);
create index api_request_logs_errors_idx
  on public.api_request_logs (requested_at desc)
  where error_message is not null;
create index fixture_injuries_team_id_idx
  on public.fixture_injuries (team_id) where team_id is not null;
create index fixture_injuries_player_id_idx
  on public.fixture_injuries (player_id) where player_id is not null;
create index fixture_odds_snapshots_fixture_fetched_idx
  on public.fixture_odds_snapshots (fixture_id, fetched_at desc);
create index fixture_external_predictions_fixture_fetched_idx
  on public.fixture_external_predictions (fixture_id, fetched_at desc);

-- Reuse the existing hardened timestamp trigger function.
create trigger competitions_set_updated_at
before update on public.competitions
for each row execute function public.set_updated_at();

create trigger competition_seasons_set_updated_at
before update on public.competition_seasons
for each row execute function public.set_updated_at();

create trigger teams_set_updated_at
before update on public.teams
for each row execute function public.set_updated_at();

create trigger venues_set_updated_at
before update on public.venues
for each row execute function public.set_updated_at();

create trigger fixture_events_set_updated_at
before update on public.fixture_events
for each row execute function public.set_updated_at();

create trigger fixture_team_statistics_set_updated_at
before update on public.fixture_team_statistics
for each row execute function public.set_updated_at();

create trigger players_set_updated_at
before update on public.players
for each row execute function public.set_updated_at();

create trigger fixture_player_statistics_set_updated_at
before update on public.fixture_player_statistics
for each row execute function public.set_updated_at();

create trigger lineups_set_updated_at
before update on public.lineups
for each row execute function public.set_updated_at();

create trigger lineup_players_set_updated_at
before update on public.lineup_players
for each row execute function public.set_updated_at();

create trigger api_sync_status_set_updated_at
before update on public.api_sync_status
for each row execute function public.set_updated_at();

create trigger api_request_logs_set_updated_at
before update on public.api_request_logs
for each row execute function public.set_updated_at();

create trigger fixture_injuries_set_updated_at
before update on public.fixture_injuries
for each row execute function public.set_updated_at();

create trigger fixture_optional_sync_status_set_updated_at
before update on public.fixture_optional_sync_status
for each row execute function public.set_updated_at();

-- Every table in the exposed public schema gets RLS, even though ingestion
-- tables are intentionally not made available to anon/authenticated clients.
alter table public.competitions enable row level security;
alter table public.competition_seasons enable row level security;
alter table public.teams enable row level security;
alter table public.venues enable row level security;
alter table public.fixture_events enable row level security;
alter table public.fixture_team_statistics enable row level security;
alter table public.players enable row level security;
alter table public.fixture_player_statistics enable row level security;
alter table public.lineups enable row level security;
alter table public.lineup_players enable row level security;
alter table public.api_sync_status enable row level security;
alter table public.api_request_logs enable row level security;
alter table public.fixture_injuries enable row level security;
alter table public.fixture_odds_snapshots enable row level security;
alter table public.fixture_external_predictions enable row level security;
alter table public.fixture_optional_sync_status enable row level security;

revoke all on table public.competitions from anon, authenticated, service_role;
revoke all on table public.competition_seasons from anon, authenticated, service_role;
revoke all on table public.teams from anon, authenticated, service_role;
revoke all on table public.venues from anon, authenticated, service_role;
revoke all on table public.fixture_events from anon, authenticated, service_role;
revoke all on table public.fixture_team_statistics from anon, authenticated, service_role;
revoke all on table public.players from anon, authenticated, service_role;
revoke all on table public.fixture_player_statistics from anon, authenticated, service_role;
revoke all on table public.lineups from anon, authenticated, service_role;
revoke all on table public.lineup_players from anon, authenticated, service_role;
revoke all on table public.api_sync_status from anon, authenticated, service_role;
revoke all on table public.api_request_logs from anon, authenticated, service_role;
revoke all on table public.fixture_injuries from anon, authenticated, service_role;
revoke all on table public.fixture_odds_snapshots from anon, authenticated, service_role;
revoke all on table public.fixture_external_predictions from anon, authenticated, service_role;
revoke all on table public.fixture_optional_sync_status from anon, authenticated, service_role;

grant select, insert, update on table public.competitions to service_role;
grant select, insert, update on table public.leagues to service_role;
grant select, insert, update on table public.competition_seasons to service_role;
grant select, insert, update on table public.teams to service_role;
grant select, insert, update on table public.venues to service_role;
grant select, insert, update on table public.fixture_events to service_role;
grant select, insert, update on table public.fixture_team_statistics to service_role;
grant select, insert, update on table public.players to service_role;
grant select, insert, update on table public.fixture_player_statistics to service_role;
grant select, insert, update on table public.lineups to service_role;
grant select, insert, update on table public.lineup_players to service_role;
grant select, insert, update on table public.api_sync_status to service_role;
grant select, insert, update on table public.api_request_logs to service_role;
grant select, insert, update on table public.fixture_injuries to service_role;
grant select, insert on table public.fixture_odds_snapshots to service_role;
grant select, insert on table public.fixture_external_predictions to service_role;
grant select, insert, update on table public.fixture_optional_sync_status to service_role;

revoke all on sequence public.competitions_id_seq from anon, authenticated;
revoke all on sequence public.competition_seasons_id_seq from anon, authenticated;
revoke all on sequence public.teams_id_seq from anon, authenticated;
revoke all on sequence public.venues_id_seq from anon, authenticated;
revoke all on sequence public.fixture_events_id_seq from anon, authenticated;
revoke all on sequence public.players_id_seq from anon, authenticated;
revoke all on sequence public.lineups_id_seq from anon, authenticated;
revoke all on sequence public.lineup_players_id_seq from anon, authenticated;
revoke all on sequence public.api_sync_status_id_seq from anon, authenticated;
revoke all on sequence public.api_request_logs_id_seq from anon, authenticated;
revoke all on sequence public.fixture_injuries_id_seq from anon, authenticated;
revoke all on sequence public.fixture_odds_snapshots_id_seq from anon, authenticated;
revoke all on sequence public.fixture_external_predictions_id_seq from anon, authenticated;

grant usage, select on sequence public.competitions_id_seq to service_role;
grant usage, select on sequence public.competition_seasons_id_seq to service_role;
grant usage, select on sequence public.teams_id_seq to service_role;
grant usage, select on sequence public.venues_id_seq to service_role;
grant usage, select on sequence public.fixture_events_id_seq to service_role;
grant usage, select on sequence public.players_id_seq to service_role;
grant usage, select on sequence public.lineups_id_seq to service_role;
grant usage, select on sequence public.lineup_players_id_seq to service_role;
grant usage, select on sequence public.api_sync_status_id_seq to service_role;
grant usage, select on sequence public.api_request_logs_id_seq to service_role;
grant usage, select on sequence public.fixture_injuries_id_seq to service_role;
grant usage, select on sequence public.fixture_odds_snapshots_id_seq to service_role;
grant usage, select on sequence public.fixture_external_predictions_id_seq to service_role;

revoke all on function public.sync_fixture_compatibility() from public, anon, authenticated;
grant execute on function public.sync_fixture_compatibility() to service_role;

comment on column public.fixtures.fixture_date_lima is
  'Derived America/Lima wall-clock timestamp; fixture_date_utc remains canonical.';
comment on column public.api_request_logs.request_hash is
  'Hash of endpoint plus canonical parameters; API credentials must never be included.';
comment on table public.fixture_odds_snapshots is
  'Append-only API-Football odds responses; identical payloads deduplicate by response hash.';
comment on table public.fixture_external_predictions is
  'Reference predictions from external providers, never the application model output.';
